import { Faq } from "../faq";
import { FinanceCalculator } from "../finance-calculator";
import { Hero } from "../hero";
import { financeFaqs, partnerCopy } from "../../lib/content";

export function FinanceSection() {
  return <div id="finance" className="page-chapter">
    <Hero compact eyebrow="Xiaomi Auto Financing · Germany" title="More ways to drive your Xiaomi." body="Choose a clear, flexible plan for your Xiaomi SU7 Ultra—with terms designed around your budget, mileage and ownership plans." primary={{href:"/#finance-calculator",label:"Estimate your payment"}} secondary={{href:"/#finance-products",label:"Compare products"}} partnerLine={partnerCopy.finance}/>
    <section className="section benefit-row">{[["One connected journey","From configuration and application to contract support."],["Transparent by design","See deposit, monthly payment, term and final amount clearly."],["Made to fit","Adjust term, initial payment and annual mileage."],["Support that continues","Access documents, guidance and contract help when you need it."]].map(([title,body],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{body}</p></article>)}</section>
    <section className="section" id="finance-products"><div className="section-heading centered"><p className="eyebrow">Choose your route</p><h2>Two ways to make it yours.</h2><p>Start with how you want to use the car. The payment structure follows.</p></div><div className="finance-products"><article><span className="pill">Ownership path</span><h3>Balloon Finance</h3><p>A deposit and fixed monthly payments, followed by a larger final payment. Designed for lower regular payments and the option to own the vehicle after settling the agreement.</p><ul><li>36, 48 or 60 months</li><li>Adjustable initial payment</li><li>Agreed final payment</li><li>Ownership after full settlement</li></ul><a className="text-link" href="#finance-calculator">Build an illustration →</a></article><article><span className="pill">Use & return</span><h3>Operating Lease</h3><p>Pay for the agreed use of your Xiaomi rather than purchasing it. Monthly rentals reflect the term, mileage and expected value when the vehicle is returned.</p><ul><li>36, 48 or 60 months</li><li>Agreed annual mileage</li><li>No resale process</li><li>Return at end of term</li></ul><a className="text-link" href="#finance-calculator">Build an illustration →</a></article></div></section>
    <section className="section comparison-section"><div className="section-heading"><p className="eyebrow">At a glance</p><h2>Compare the essentials.</h2></div><div className="finance-compare"><div><strong>Your priority</strong><span>Balloon Finance</span><span>Operating Lease</span></div>{[["Typical goal","Own later","Use and return"],["Monthly structure","Lower regular payments","Predictable rentals"],["End of term","Final payment due","Vehicle returned"],["Mileage","Helps shape the offer","Contractual allowance"],["Residual value risk","Customer ownership exposure","Usually held by provider"]].map(row=><div key={row[0]}>{row.map((cell,index)=>index===0?<strong key={cell}>{cell}</strong>:<span key={cell}>{cell}</span>)}</div>)}</div></section>
    <section className="section calculator-section" id="finance-calculator"><div className="section-heading"><p className="eyebrow">Finance calculator</p><h2>Shape an illustrative plan.</h2><p>See how product, deposit, term and mileage change the monthly figure.</p></div><FinanceCalculator /></section>
    <section className="section soft-section"><div className="section-heading"><p className="eyebrow">How it works</p><h2>From configuration to the road.</h2></div><div className="steps-grid">{[["01","Configure","Choose your SU7 Ultra specification."],["02","Select","Compare Balloon Finance and Operating Lease."],["03","Adjust","Set your deposit, term and annual mileage."],["04","Apply","Submit details for Santander's credit assessment."],["05","Sign & drive","Review your agreement, sign and take delivery."]].map(([i,t,b])=><article key={i}><span>{i}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
    <section className="section responsibility"><div><p className="eyebrow">At the end</p><h2>Know what comes next.</h2></div><article><h3>With Balloon Finance</h3><p>Pay the final amount and keep the car. Refinancing or changing vehicle may be available under the products and approval offered at that time.</p></article><article><h3>With Operating Lease</h3><p>Return the vehicle to the agreed standard. Mileage, condition, missing items and contractual responsibilities are assessed at handover.</p></article></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">Questions, answered</p><h2>Finance through every stage.</h2></div><Faq items={financeFaqs}/></section>
  </div>;
}
