import Link from "next/link";
import { Hero } from "../hero";
import { partnerCopy, principles } from "../../lib/content";

export function FinancialServicesSection() {
  return <div id="financial-services" className="page-chapter">
    <Hero eyebrow="Xiaomi Financial Services Europe" title="Simple choices. Clear protection. More freedom to move." body="A connected finance and insurance experience designed to make every step—from configuration to ownership—feel beautifully straightforward." primary={{ href: "/#finance", label: "Explore financing" }} secondary={{ href: "/#insurance", label: "Explore insurance" }} />
    <section className="section intro-section"><div className="section-heading"><p className="eyebrow">Designed around your journey</p><h2>One car. One connected experience.</h2></div><p className="lede">Xiaomi brings the vehicle, digital journey, financing and protection together in one clear path. Understand your options, continue with trusted providers and manage what comes next without losing momentum.</p></section>
    <section className="section split-cards">
      <article className="product-card finance-card"><span className="card-index">01 / Financing</span><h2>Drive now.<br/>Decide with confidence.</h2><p>Choose Balloon Finance for a flexible ownership path or an Operating Lease for predictable use and simple return.</p><p className="provider">{partnerCopy.finance}</p><Link className="text-link" href="/#finance">Discover financing <span>→</span></Link></article>
      <article className="product-card insurance-card"><span className="card-index">02 / Insurance</span><h2>Protection shaped<br/>around your Xiaomi.</h2><p>Compare Basis, Komfort and Premium cover, with electric-vehicle protection and direct access to an Allianz quote.</p><p className="provider">{partnerCopy.insurance}</p><Link className="text-link" href="/#insurance">Discover insurance <span>→</span></Link></article>
    </section>
    <section className="section soft-section"><div className="section-heading"><p className="eyebrow">The Xiaomi approach</p><h2>Financial services, made human.</h2></div><div className="principle-grid">{principles.map(([index,title,body])=><article key={title}><span>{index}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="section journey-section"><div className="section-heading"><p className="eyebrow">One continuous journey</p><h2>From first look to every road after.</h2></div><div className="journey">{["Discover","Configure","Finance","Insure","Apply","Delivery","Ownership"].map((step,index)=><div key={step}><span>{String(index+1).padStart(2,"0")}</span><strong>{step}</strong></div>)}</div></section>
    <section className="section market-section"><div><p className="eyebrow">Built locally, connected across Europe</p><h2>Germany, our first product market.</h2><p>Local products, service and support are designed around German consumer needs. Additional European markets will follow in phases as local products become available.</p></div><div className="market-card"><span>DE</span><div><strong>Germany</strong><small>Finance & insurance available in this demo</small></div><b>Launch market</b></div></section>
    <section className="section ecosystem"><div className="section-heading"><p className="eyebrow">A trusted service ecosystem</p><h2>Clear roles. Connected service.</h2></div><div className="role-grid"><article><h3>Xiaomi Auto</h3><p>Your vehicle and digital journey.</p></article><article><h3>Santander</h3><p>Finance provider and credit decision-maker.</p></article><article><h3>Allianz</h3><p>Insurance provider and underwriter.</p></article><article><h3>Local market teams</h3><p>Product, compliance and customer support.</p></article></div></section>
  </div>;
}
