import { Faq } from "../faq";
import { Hero } from "../hero";
import { InsuranceComparison } from "../insurance-comparison";
import { insuranceFaqs, partnerCopy } from "../../lib/content";

const allianzUrl = "https://www.allianz.de/auto/kfz-versicherung/";

export function InsuranceSection() {
  return <div id="insurance" className="page-chapter">
    <Hero compact eyebrow="Xiaomi Auto Insurance · Germany" title="Protection designed around your Xiaomi." body="From essential liability cover to broader electric-vehicle protection, compare three clear levels and continue directly to Allianz for your quote." primary={{href:allianzUrl,label:"Get a quote from Allianz",external:true}} secondary={{href:"/#insurance-cover",label:"Compare cover"}} partnerLine={partnerCopy.insurance}/>
    <section className="section benefit-row six">{[["EV-ready protection","Battery, high-voltage and charging-related cover options."],["Three clear levels","Understand liability, partial and comprehensive protection."],["Digital journey","Quote, policy and eVB routes designed for online use."],["Help when it matters","Claims, roadside and overseas guidance."],["Repair confidence","Clear approved-repair and parts standards in your policy."],["Transparent roles","Provider, policy documents and exclusions kept visible."]].map(([title,body],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{body}</p></article>)}</section>
    <section className="section" id="insurance-cover"><div className="section-heading centered"><p className="eyebrow">Choose your cover</p><h2>Three levels. One clear decision.</h2><p>Start with what you want to protect, then review the final Allianz policy wording.</p></div><div className="tier-grid">{[["Basis","Essential confidence","Motor liability with essential support for everyday driving."],["Komfort","Balanced protection","A broader blend of vehicle, roadside and EV protection.","Recommended"],["Premium","Complete reassurance","Comprehensive protection for your vehicle, travel and ownership experience."]].map(([name,tagline,body,badge])=><article className={badge?"featured":""} key={name}>{badge&&<span className="recommend">{badge}</span>}<p className="eyebrow">{tagline}</p><h3>{name}</h3><p>{body}</p><a className="text-link" href={allianzUrl} target="_blank" rel="noreferrer">Continue to Allianz ↗</a></article>)}</div></section>
    <section className="section comparison-section"><div className="section-heading"><p className="eyebrow">Cover comparison</p><h2>See the difference clearly.</h2></div><InsuranceComparison/></section>
    <section className="section soft-section"><div className="section-heading"><p className="eyebrow">Your quote journey</p><h2>From details to eVB.</h2></div><div className="steps-grid four">{[["01","Get your quote","Continue to Allianz for a personalised price."],["02","Add your details","Vehicle, drivers, annual mileage and SF class."],["03","Choose protection","Select cover, deductible and available EV options."],["04","Confirm & register","Complete the policy and receive your eVB where applicable."]].map(([i,t,b])=><article key={i}><span>{i}</span><h3>{t}</h3><p>{b}</p></article>)}</div><a className="button centered-button" href={allianzUrl} target="_blank" rel="noreferrer">Get a quote from Allianz ↗</a></section>
    <section className="claims-section"><div className="claims-copy"><p className="eyebrow">Claims & assistance</p><h2>When something happens, know what to do.</h2><p>Access Allianz claims support, roadside assistance, towing, repair guidance and help while travelling. In an emergency, contact the emergency services first.</p><a className="button light" href="https://www.allianz.de/service/schaden-melden/" target="_blank" rel="noreferrer">Go to Allianz claims ↗</a></div><div className="claims-list"><p>Have these ready</p>{["Policy number","Vehicle registration","Location and time","Photos of the incident","Police record, when applicable"].map((item,index)=><div key={item}><span>{index+1}</span>{item}</div>)}</div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">Protection in real life</p><h2>Designed for the journeys you make.</h2></div><div className="scenario-grid"><article><span>City</span><h3>A busy-street accident</h3><p>Clear claims guidance and repair support help turn an unexpected moment into a manageable next step.</p></article><article><span>Electric</span><h3>A charging incident</h3><p>Understand how your selected policy treats charging equipment, cables and high-voltage components.</p></article><article><span>Europe</span><h3>A cross-border road trip</h3><p>Check territorial cover and assistance before departure, with support information close at hand.</p></article></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">Questions, answered</p><h2>Insurance without the jargon.</h2></div><Faq items={insuranceFaqs}/></section>
    <section className="section contact-panel" id="support"><div><p className="eyebrow">Xiaomi Financial Services support</p><h2>Ready to take the next step?</h2><p>Our demo support team can explain finance structures and application steps. Continue to Allianz for insurance eligibility, pricing and final policy wording.</p></div><div><small>Demo contact details</small><a href="tel:+498009460000">+49 800 946 0000</a><a href="mailto:financialservices-demo@xiaomi.com">financialservices-demo@xiaomi.com</a><small>Insurance provider</small><strong>Allianz</strong><a href={allianzUrl} target="_blank" rel="noreferrer">Get a quote ↗</a></div></section>
  </div>;
}
